### ISSUE TITLE
More elegant way to show the path history

### ISSUE THREAD

**Issue by amitbha** [doublecmd/doublecmd.github.io#2]
version: 0.8.1 gtk3
Press the "Ctrl + H" to view the path history, which's a very very long list.
It will be more elegant to show list in a window with search function.
Like below:
![2018-01-25 18-40-39](https://user-images.githubusercontent.com/4060625/35384724-38fad5b4-0201-11e8-97cf-68b7ca54a89c.png)

**Comment by denis-bisson** [comment]
Hi! Thank you for your input. But with current 0.8.1 beta version, I think we may already do something similar to what you're writing here. It's simply that it is not activated by default. Go in "**Options -> Layout -> Tree View Menu**" and activate it for the history. Also, as you may see, you'll be able to activate it also for directory hotlist and for favorite tabs.

Also, maybe I am a little "picky" but this is more a suggestion or a wish than an "issue" and may be written in the forum of DC.

Denis.

**Comment by amitbha** [comment]
Thanks for your reply. 
The "Tree View Menu" is awesome! I think it's time to know more about DC's new function.  
BTW, is there any plan to improve the function of cmd line?  such as command/path completion?

-------
Sorry for the bother. It's a not an issue but a feature request in github. 
I just had a github account, so... ☻
I will go to the forum next time.
