### ISSUE TITLE
Time for a new documentation release?

### ISSUE THREAD

**Issue by ginggs** [doublecmd/doublecmd.github.io#25]
Double Commander 0.9.7 will be in Ubuntu 20.04 to be released in April 2020.
(unless there's another release before Feature Freeze at the end of February)

Has much changed in the documentation since 0.9.3?

**Comment by Skif-off** [comment]
> Has much changed in the documentation since 0.9.3?

Under each title of release you can find link "N commits to master since this release".

P.S. About release: see [FAQ 2.2](http://doublecmd.github.io/doc/en/faq.html#repo)

**Comment by alexx2000** [comment]
It has some changes and fixes, so why not. Done.
