### ISSUE TITLE
New documentation release for 0.9.10?

### ISSUE THREAD

**Issue by ginggs** [doublecmd/doublecmd.github.io#36]
I've uploaded Double Commander 0.9.10 to Debian and it should be included in the upcoming Debian 11 bullseye and Ubuntu 21.04 releases.
https://tracker.debian.org/pkg/doublecmd

Have there been enough changes in the documentation since 0.9.7 to tag a new release for 0.9.10?

**Comment by alexx2000** [comment]
Yes. I made 0.9.10 release.
